csm_FragNormal = coat.bump;
csm_ClearcoatNormal = coat.bump;
csm_Roughness = coat.roughness;
csm_Iridescence = coat.iridescence;
csm_Emissive = coat.color * coat.emission;
csm_Clearcoat = uClearcoat;
csm_ClearcoatRoughness = uClearcoatRoughness;
csm_Metalness = coat.metallic;
// csm_Transmission = 1.0;
