import STRUCTS_DEFINITION from "./structs";

import { UNIFORMS } from "./uniforms";
import { VARYINGS_SOLID, VARYINGS_WIRE } from "./varyings";
import VERTEX_BODY from "./meta/vertex.glsl?raw";
import FRAGMENT_BODY from "./meta/fragment.glsl?raw";
import SOLID_PARAMETERS from "./meta/parameters.glsl?raw";
import type { ShaderPreset } from "./presets";
import PRESETS from "./presets";
import type { MaterialType } from "./types";
import { includeStdLib } from "./stdlib";
import { FFT_SIZE } from "../constants";

export type CompilerMetadata = {
  shaderType: "vertex" | "fragment";
  preset: ShaderPreset;
  presetStyle: MaterialType;
  defines?: Record<string, string>;
};

export function compile(metadata: CompilerMetadata): string {
  const varyings = generateVaryings(metadata.presetStyle, metadata.shaderType);
  const defines = generateDefines(
    metadata.defines,
    metadata.shaderType,
    metadata.presetStyle
  );
  const implementation = generateImplementation(metadata.preset);
  const body = generateShaderBody(metadata.presetStyle, metadata.shaderType);
  return `
// Generated by cumpiler.
// ${metadata.presetStyle} ${metadata.shaderType} ${metadata.preset}

// Uniforms;
${UNIFORMS}
// crutch for declaring array
uniform int uFFT[${FFT_SIZE}]; 

// Varyings;
${varyings}

// Defines;
${defines}

// Structs;
${STRUCTS_DEFINITION}

// Implementation;
${implementation}

// Body;
${body}

// End of shader.
  `;
}

function generateVaryings(
  presetStyle: MaterialType,
  shaderType: "vertex" | "fragment"
): string {
  return Object.entries(
    presetStyle === "solid" ? VARYINGS_SOLID : VARYINGS_WIRE
  )
    .map(
      ([vkey, vtype]) =>
        `${
          shaderType === "fragment" && vkey === "vNormal" ? "//" : ""
        } varying ${vtype} ${vkey};`
    )
    .join("\n");
}

function generateDefines(
  data: Record<string, string> = {},
  shaderType: "vertex" | "fragment",
  presetStyle: MaterialType
): string {
  return Object.entries({
    ...data,
    VERTEX: +(shaderType === "vertex"),
    IS_SOLID: +(presetStyle === "solid"),
    IS_POINT: +(presetStyle === "point"),
    IS_WIRES: +(presetStyle === "wireframe"),
  })
    .map(([dkey, dvalue]) => {
      return `#define ${dkey} ${dvalue}`;
    })
    .join("\n");
}

function generateImplementation(preset: ShaderPreset): string {
  return includeStdLib(PRESETS[preset]);
}

function generateShaderBody(
  presetStyle: MaterialType,
  shaderType: "vertex" | "fragment"
) {
  return shaderType === "vertex"
    ? VERTEX_BODY
    : FRAGMENT_BODY.replace(
        "//#inlude<solid_parameters>",
        presetStyle === "solid" ? SOLID_PARAMETERS : "// solid params ignored. "
      ).replace(
        "//#inlude<vNormal>",
        presetStyle === "solid" ? "vNormal," : "vec3(0.),"
      );
}
