import type { UniformKey, GlslType } from "./types";

export const UNIFORM_KEYS = [
  "uTime",
  "uSeed",
  "uColor1",
  "uColor2",
  "uColor3",
  "uColor4",
  "uColor5",
  "uUseColorKey",
  "uColorKeyValue",
  "uColorNoiseScale",
  "uDisplacementNoiseScale",
  "uDisplacementAmplitude",
  "uRoughness",
  "uClearcoat",
  "uClearcoatRoughness",
  "uIridescence",
  "uLineWidth",
  "uLineCount",
  "uNoiseOffset",
  "uRoughnessPattern",
  "uNoiseVariant",
  "uStripesWidth",
  "uEmission",
  "uFFT",
  "uRMS",
] as const;

export const UNIFORM_TYPES: Record<UniformKey, GlslType> = {
  uTime: "float",
  uSeed: "float",
  uColor1: "vec3",
  uColor2: "vec3",
  uColor3: "vec3",
  uColor4: "vec3",
  uColor5: "vec3",
  uUseColorKey: "float",
  uColorKeyValue: "float",
  uColorNoiseScale: "float",
  uDisplacementNoiseScale: "float",
  uDisplacementAmplitude: "float",
  uRoughness: "float",
  uClearcoat: "float",
  uClearcoatRoughness: "float",
  uIridescence: "float",
  uLineWidth: "float",
  uLineCount: "int",
  uNoiseOffset: "vec3",
  uRoughnessPattern: "float",
  uNoiseVariant: "float",
  uStripesWidth: "float",
  uEmission: "float",
  uFFT: "int|[32]",
  uRMS: "float",
};

export const GLSL_TYPES = [
  "float",
  "int",
  "vec2",
  "vec3",
  "vec4",
  "int|[32]" /* array test */,
] as const;
