import STRUCTS_DEFINITION from "./structs";

import { UNIFORM_KEYS, UNIFORM_TYPES } from "./uniforms";
import { VARYINGS_SOLID, VARYINGS_WIRE } from "./varyings";
import VERTEX_BODY from "./meta/vertex.glsl?raw";
import FRAGMENT_BODY from "./meta/fragment.glsl?raw";
import SOLID_PARAMETERS from "./meta/parameters.glsl?raw";
import type { ShaderPreset } from "./presets";
import PRESETS from "./presets";

type CompilerMetadata = {
  shaderType: "vertex" | "fragment";
  presetType: "solid" | "wireframe";
  preset: ShaderPreset;
  defines: Record<string, string>;
};

export function compile(metadata: CompilerMetadata): string {
  const uniforms = generateUniforms();
  const varyings = generateVaryings(metadata.presetType, metadata.shaderType);
  const defines = generateDefines(metadata.defines);
  const implementation = generateImplementation(metadata.preset);
  const body = generateShaderBody(metadata.presetType, metadata.shaderType);
  return `
// Generated by cumpiler.
// ${metadata.presetType} ${metadata.shaderType} ${metadata.preset}

// Uniforms;
${uniforms}

// Varyings;
${varyings}

// Defines;
${defines}

// Structs;
${STRUCTS_DEFINITION}

// Implementation;
${implementation}

// Body;
${body}

// End of shader.
  `;
}

function generateUniforms(): string {
  return UNIFORM_KEYS.map((ukey) => {
    return `uniform ${UNIFORM_TYPES[ukey]} ${ukey};`;
  }).join("\n");
}

function generateVaryings(
  presetType: "solid" | "wireframe",
  shaderType: "vertex" | "fragment"
): string {
  return Object.entries(presetType === "solid" ? VARYINGS_SOLID : VARYINGS_WIRE)
    .map(
      ([vkey, vtype]) =>
        `${
          shaderType === "fragment" && vkey === "vNormal" ? "//" : ""
        } varying ${vtype} ${vkey};`
    )
    .join("\n");
}

function generateDefines(data: Record<string, string> = {}): string {
  return Object.entries(data)
    .map(([dkey, dvalue]) => {
      return `#define ${dkey} ${dvalue}`;
    })
    .join("\n");
}

function generateImplementation(preset: ShaderPreset): string {
  return PRESETS[preset];
}

function generateShaderBody(
  presetType: "solid" | "wireframe",
  shaderType: "vertex" | "fragment"
) {
  return shaderType === "vertex"
    ? VERTEX_BODY
    : FRAGMENT_BODY.replace(
        "//#inlude<solid_parameters>",
        presetType === "solid" ? SOLID_PARAMETERS : "// solid params ignored. "
      );
}

/*
//#include<uniforms>
//#include<varyings>
//#include<defines>
//#include<structs>

//#include<implementation>

void main() {
  //#include<shader_body>
}


*/
